### PR TITLE
Add sftp support for publish 

### PR DESCRIPTION
**Pull request by danghai**
I make PR to add sftp support for `publish` to transfer the kernel tarball, configuration, and build information to the specified location. I also add docstring.

### CODE REVIEW

**Comment by danghai** [comment]
@veruu I apply the `sftp` being the same as `scp` command. 
`scp <source> <destination>`.
`sftp <source> <destination>`.
I think `sftp` is the same as `scp`. So I just write a simple `subprocess` call being the same `scp`.

**Comment by danghai** [comment]
@veruu yeah I tried before. But I save it another computer. I will look at it soon. What about the docstrings?

**Comment by veruu** [comment]
The docstrings are OK. I can merge that patch if you submit it via a separate pull request (can't merge only selected patches from the pull).

**Comment by danghai** [comment]
@veruu Okay, I create another PR #310 . I will look at this PR more.

**Comment by danghai** [comment]
@veruu right, it is actually different. I may have the mistake before I use `sftp` to get the data from host. It may be the same way as `scp`. However, uploading/ transferring data from host computer to server is different. I update my commit. Thanks

**Comment by danghai** [comment]
@veruu . Thanks. I forget update the `README` and fix one type though.  :(

**Comment by veruu** [comment]
That can be done in another pull, no problem :)

**Pull request merged**
