### PR TITLE
BeakerRunner.dumpjunitresult() accept output filename

### LINKED ISSUE #273: BeakerRunner.dumpjunitresults() should accept output filename
At the moment, `BeakerRunner.dumpjunitresults()` accepts a directory to write the junit file to, and it just assumes that it can generate a sufficiently distinct filename to not clash with existing files. It cannot know that, since it's not actually creating the directory and filling it with files. Instead, the caller should decide how the output file should be named, and the function should accept a full name of the file to write to.

### PR DESCRIPTION
**Pull request by danghai**
I make PR for `BeakerRunner.dumpjunitresult()` accepting the output file name
Fixes #273

### CODE REVIEW

**Comment by danghai** [comment]
@veruu yeah. I am not sure how to fix `flake8` violation when I use the new join function. For the test file, I see it only test the file create in this directory or not? And I do not know what I need to test when I pass the filename argument.

**Comment by veruu** [comment]
I can't help you if you don't mention the error you get ;) For the test, I'd say you should create a filename inside the junit directory and pass that instead of the directory, and change the name of the expected file to match that.

**Comment by danghai** [comment]
@veruu Thanks review. It is a good idea for me to write the test case. I think I am going to wait the opinion's @spbnick for this patch first.

**Comment by danghai** [comment]
Because `dumpjunitresult()` method is removed, so I close this PR now.

**Pull request closed without merging**
