### PR TITLE
Use new state file

### PR DESCRIPTION
**Pull request by major**
- [x] Requires #157 to merge first.
- [x] Requires #160 to merge first.

### CODE REVIEW

**Comment by major** [comment]
Hold off on merging this one -- I need to roll through and see where `cfg` needs to be replaced with `state`.

**Comment by major** [comment]
Nevermind, it looks like I misunderstood the logic there for a moment. This should be okay to review.

**Comment by dzickusrh** [comment]
This can be come confusing unless we set the ground rules right.
I think 'state' should contain all the runtime needed data.  That includes the initial cfg data.  After the state file is created, we should no longer use 'cfg' for the rest of the commands.
Treat 'state' as a copy of 'cfg' plus whatever else is needed, sort of how it is mimic'd today (missing the copy).

**Comment by dzickusrh** [comment]
This also avoids any changes to the cfg file during a run.

**Comment by major** [comment]
That does make some sense, and I'd like to keep `cfg` immutable. We wouldn't change a user's command line input or their config file, so we shouldn't touch those variables either. The `load_config()` method makes this a little tricky.

I'll try to get a look at this tomorrow.

**Pull request closed without merging**
