### PR TITLE
Set default in parser

### PR DESCRIPTION
**Pull request by danghai**
I make PR to set default in parser. I think by explicitly setting the default value in parser, it reduces the
`if condition` case in source code.

### CODE REVIEW

**Comment by veruu** [comment]
Setting the default in the parser means we will ignore the options passed via the configuration file. Question is whether we don't mind it -- I think these specific options should be passed via command line only and the change is OK, but this needs more input from others. @major, what do you think?

**Comment by danghai** [comment]
@veruu oh I see.  The options in configuration file will not work in this case. I remember ( not sure) Nick told me he probably removes/changes configuration file in the future.

**Comment by danghai** [comment]
It may require more input rather from command line rather than configuration file. What do you think @major ?

**Comment by major** [comment]
If I remember correctly, @spbnick was heavily against this change (I proposed something similar a while back) because we still have a mess with the config file and command line argument precedence. Perhaps we should fix that mess first? :)

**Comment by spbnick** [comment]
Yeah, we cannot have defaults in the parser, because we have configuration. We need to remove (most of) it, and then we should be able to do it. Closing for now. Thank you, Hai!

**Pull request closed without merging**
