### PR TITLE
Document all the code in skt/executable.py

### PR DESCRIPTION
**Pull request by idorax**
This PR only updates code in file skt/executable.py

### CODE REVIEW

**Comment by idorax** [comment]
Fixed issue "E501 line too long (80 > 79 characters)"

**Comment by veruu** [comment]
Can we squash the commits into a single one (and rebase)?

**Comment by spbnick** [comment]
@idorax, do you think you could rebase your work and make it a single commit? Ping me, if you need help.

**Comment by veruu** [comment]
LGTM, but I'll wait with merging in case @spbnick has some additional comments.

**Comment by spbnick** [comment]
Looks great, thank you, Vector and Veronika! Merged!

**Pull request merged**
