### PR TITLE
Add basic .travis.yml

### PR DESCRIPTION
**Pull request by spbnick**

### CODE REVIEW

**Comment by spbnick** [comment]
@agustinhenze, do you think this .travis.yml is alright, or should we change/add something?

**Comment by spbnick** [comment]
I see we don't have python2-mock dependency in there. Perhaps we should have it explicitly?

**Comment by spbnick** [comment]
Alright, added the explicit "mock" dependency, even though it's already installed on Travis CI, just in case.

**Comment by spbnick** [comment]
Merged.

**Comment by agustinhenze** [comment]
Sorry, I couldn't answer before. Yes, totally agree about adding mock explicitly. We have CI! Awesome!

**Pull request closed without merging**
