### PR TITLE
Merge fixes

### PR DESCRIPTION
**Pull request by spbnick**
These are various fixes for merging issues encountered during merging in containers. We need these in ASAP, but please take a careful look through them. Thanks!

### CODE REVIEW

**Comment by spbnick** [comment]
Argh, completely missed your review. How would you prefer this done?

**Comment by spbnick** [comment]
Merging now, but let's discuss the proper approach/report issues to refactor this. Thank you, Veronika!

**Comment by veruu** [comment]
I'd have to take a proper look at the containers and things around to see how it can be simplified, if `git am --abort` failing doesn't mean a serious problem which shouldn't be caught etc. It's not a huge problem that would need immediate solving, I just find nesting like this slightly unclear.

**Comment by spbnick** [comment]
I see, thank you the explanation. Yeah, I think we should abort completely, if `git am --abort` fails, because that would indicate a serious problem, likely breaking Git repo consistency. We shouldn't just e.g. go on applying patches. I didn't think this through well enough. However, we should preserve information on the original failure too, even if `git am --abort` fails.

**Comment by spbnick** [comment]
Now reading the above, I don't think I'm thinking well enough today :)

**Comment by veruu** [comment]
Sounds good! Let's save the failure first, and then run the `--abort`. If that fails, we already have all the info and can safely exit. Can you file an issue for it, so we don't forget to take a look later?

**Comment by spbnick** [comment]
Alright, my rather lame attempt at it is in #229 :smiley:

**Pull request merged**
