### PR TITLE
Mark skt.KernelBuilder private methods

### LINKED ISSUE #10: Mark all private class methods as such
To avoid exposing too much interface, prepend all private class method names with __ to have them recognized as such.

### PR DESCRIPTION
**Pull request by danghai**
I make PR to mark `skt.KernelBuilder` private methods. It violates the flake8 because the line > 79. I am not sure how to handle that. Could you help me review them? Thanks
Fix #10 .

### CODE REVIEW

**Comment by danghai** [comment]
@veruu I can fix the `flake8` issue now. But I got issue in `pylint`. The bad thing is I disable protected-access in pylint :(

**Comment by veruu** [comment]
@danghai it's ok to disable that for tests, since how else would we test it? However, Travis is still failing. Can you resolve that?

**Comment by danghai** [comment]
@veruu Yeah, I resolve that by disabling `E1101` in pylint

**Comment by danghai** [comment]
@veruu That makes sense!. I fixed it

**Comment by danghai** [comment]
@veruu I fixed it. Could you review it now?

**Comment by danghai** [comment]
@veruu Okay, I squash 2 commits into 1. If It is good, I am going to do all for the rest of the file.

**Comment by veruu** [comment]
Thanks Hai!

**Pull request merged**
