### PR TITLE
Add coverage % to README

### PR DESCRIPTION
**Pull request by major**

### CODE REVIEW

**Comment by spbnick** [comment]
Do you think it would be good to move the URLs to the references at the end of file, perhaps? This way readers of the raw README.md don't have to see as much garbage at the start. Something like what's done here: https://raw.githubusercontent.com/DIGImend/digimend-kernel-drivers/master/README.md ?

**Comment by danghai** [comment]
I think it is good to add badge of build/pass `travis`  too?

**Comment by major** [comment]
Oh, I think i see what we're saying here. I'll take another look and push an update this morning.

**Comment by major** [comment]
Oh, I think i see what we're saying here. I'll take another look and push an update this morning.

**Pull request merged**
