### PR TITLE
Remove version constraint for pycodestyle (new release of flake8)

### PR DESCRIPTION
**Pull request by agustinhenze**
On the last release of flake8 the dependency version for pycodestyle was bumped to >= 2.4.0 and there is no newer version for pycodestyle yet i.e. skt is not installable.

### CODE REVIEW

**Comment by spbnick** [comment]
The change is good, of course, but why do we get Travis CI failures?

**Comment by agustinhenze** [comment]
> The change is good, of course, but why do we get Travis CI failures?

Because the new release of `flake8` :man_facepalming:.
```
flake8 runtests: commands[0] | flake8 --show-source .
./skt/kernelbuilder.py:79:11: W605 invalid escape sequence '\g'
        return re.sub(r"[]*?[]", "[\g<0>]", pathname)
          ^
ERROR: InvocationError for command '/home/travis/build/RH-FMK/skt/.tox/flake8/bin/flake8 --show-source .' (exited with code 1)
```
And it seems a false positive...

**Comment by veruu** [comment]
Marking the second string as raw should fix it, unless anything changed since I ran into the error

**Comment by agustinhenze** [comment]
Oh, you're right I saw the `r` on the beginning and got confused... Pushing the fix

**Comment by agustinhenze** [comment]
This PR will be needed for `production` and for `staging`  otherwise all pipelines will fail.

**Comment by spbnick** [comment]
And they're failing, thank you, Agustin!

**Pull request merged**
